# Generated by Django 4.2.17 on 2024-12-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discriptions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
