# Generated by Django 4.2.17 on 2024-12-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_discriptions_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='main_catego_name_5111b9_idx',
            old_name='users_categ_name_bcdc62_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='main_produc_id_f4bffc_idx',
            old_name='users_produ_id_7d1d32_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='main_produc_name_168fc5_idx',
            old_name='users_produ_name_bf6596_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='main_produc_created_15eff9_idx',
            old_name='users_produ_created_367bb5_idx',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
